[DEFAULT]
enable_mc = False
default_cluster = dlp

[dlp]
enable_mc = False
boto = True
access_key = 45DJ69SBDGDFITJT9PCD
secret_key = oiWI7NP3O3g1UOkEzuzJSZLWkBJpv2a5mcuShCRd
host_base = http://auto-internal.st-sh-01.sensecoreapi-oss.cn
# host_base = http://aoss-v2.st-sh-01.sensecoreapi-oss.cn
