[DEFAULT]
enable_mc = False
default_cluster = pl_predcition_model

[pl_predcition_model]
enable_mc = False
boto = True
access_key = 019A0FAE16F6760088BC7687D4798535
secret_key = 019A0FAE16F675F2A007E0EABE04C992
host_base = http://aoss-internal-v2.st-sh-01.sensecoreapi-oss.cn
# host_base = http://aoss-v2.st-sh-01.sensecoreapi-oss.cn