[DEFAULT]
enable_mc = False
default_cluster = dlp

[dlp]
enable_mc = False
boto = True
access_key = O5B34FE51MMZRZGEY1Z5
secret_key = Xh6hOX5xnZ6BrsNnCcCt8NzNCbWeCSYwtABErKJ6
host_base = http://auto-internal.st-sh-01.sensecoreapi-oss.cn
