[DEFAULT]
enable_mc = False
default_cluster = dlp

[dlp]
enable_mc = False
boto = True
access_key = D638E80B225D4C26BA197ADFB030E49B
secret_key = 37BDD7CB24EF4986B5C7AB6CD24EC2D0
host_base = http://aoss-internal-v2.st-sh-01.sensecoreapi-oss.cn